binder/router.py
binder/views.py

In Django 1.10, doing a GET on a route results in: `ValueError: invalid literal for int() with base 10: ''`. Following the stacktrace, this is because of something Django does in `request.body`.
So apparently, using `request.body` on a GET request will now result in this error.
According to the tests I did, `request._post` is always available when `request.body` is accessible without an error.
Maybe it's cleaner to only log `request.body` when the method is not `HEAD` or `GET`? Didn't yet test if that would work though.
This is not yet tested on Django 1.9.

Fix `log_request_body` failing on Django 1.10

---

binder/views.py
tests/test_model_view_basics.py

When creating a model, it's nice to be able to get all the related values so it's possible to build a complete view of the model with an extra fetch.
So, this PR adds complete support for `withs` for `PUT` and `POST` requests.
EDIT: Travis failure is unrelated and is fixed by https://github.com/CodeYellowBV/django-binder/pull/35

add ?with=related_model to POST/PUT requests

---

binder/views.py

Request must now be passed in the view methods. This allows the view to always get the context of the request. This can be used to do permission checking for example.
Note that the withs parameter is now sometimes necessary too. A possible solution for this is to swap the withs and request parameter in the _get_withs method. 
Note that this breaks backwards compatability.

Force request in modelview

---

CHANGELOG.md
binder/router.py
binder/views.py
docs/install.md
tests/test_router.py
tests/testapp/urls.py

Instead, we pass the router to the view class in kwargs, which it then
saves as a property on itself.
This allows us to instantiate multiple routers, for example in the
tests, but it also makes it easier to combine multiple apps which all
rely on Binder.
This is a backwards incompatible change!
Fixes #28

Remove singleton pattern from Router class (#28).

---

binder/json.py
tests/test_json.py

In Django you can use a Decimal field in a model, but when you do that it gives a 500 error because it can't serialize a Decimal field to JSON. This fixes that.

Add support for JSON serializing `decimal.Decimal`

---

binder/views.py

In TMS we have some dependencies that are unresolvable by multi_put. We need to write some custom code to handle this edge case. Multi_put however currently is request in > response out. For the custom dependency we cannot reuse any of the multi_put code. 
In this pull request we split the multi_put into tinier, reusable and overwritable functions, allowing custom endpoints to reuse request parsing, object collection, dependency calculation, object ordering and id_map constructing.

Split multiput into smaller, reusable functions.

---

binder/views.py
tests/test_model_view_basics.py
tests/testapp/models/__init__.py
tests/testapp/models/gate.py
tests/testapp/urls.py
tests/testapp/views/__init__.py
tests/testapp/views/gate.py

In most binder apps we use the user > profile construction.
Profile doesn't have an `id` but uses its foreign key to user as private key.
Binder however tries to filter models on `id` instead of on `pk`.
It also assumes that a foreign key for a one-to-one model is set is set on the root model.
With users and profiles this is not a case as we cannot simply alter the user model.
This PR contains a test for this user profile relation, using the existing zoo model: A gate has a zoo_id as primary key.
It also contains a fix for `pk` filtering instead of `id` filtering and for the foreign key assumption.

Use pk for relation filtering

---

binder/views.py
tests/test_model_view_basics.py
tests/testapp/models/zoo.py
tests/testapp/views/zoo.py

This pull requests add a option named `shown_properties` to the model view
In SMS we have many places where models have derived properties from other models. These derived properties can not be added to the response generated by default. At this moment there is a very slow hack to still add these  properties. This pull request will make a much faster way to add this properties to the model. 
An example of a use case:
- We have a zoo inspector, who can see certain features of the zoo. One of such features is that they can see the amount of animals belonging to the zoo
- The zoo inspector is not allowed to see the individual animals
- A solution is to keep a counter of the amount of animals in the zoo. This needs a lot of accounting to keep it correct
- Another solution is to fetch the …

Add shown properties to model view

---

binder/tests/test_filterable_relations.py
binder/views.py

Fix for issue #81 
I went with the `?where=contacts.city(name=ehv)` approach instead of the `?.contacts.city(name=ehv)`, as in the latter the query param key would contain the opening `(` and the val would contain the closing `)`.
- where on a 1tomany and a 1to1 relation
- multiple wheres in different levels of the requested relation
- a where and a filter
- where on a manytomany relation
The with tree traversal from binder is really weird. When a with is set to `animals.caretaker`, it calls `_get_with` once for `animals` once for `animals.caretaker` and once for `caretaker`, which means the queryset of the related animals is calculated twice.
Anyhow, for the where calculating I do calculate a proper tree, but the generation of this tree is a bit verbose (in `_parse_wheres`)
Also, the …

Relation filtering

---

binder/tests/test_inheritance.py
binder/tests/testapp/models/__init__.py
binder/tests/testapp/models/lion.py
binder/tests/testapp/views/__init__.py
binder/tests/testapp/views/lion.py
binder/views.py

Makes the whole negative id relation magic work for models with inheritance by also setting backrefs for subclasses of models and also saving negative ids for superclasses of created models.

Support model inheritance in multiput

---

binder/.flake8
binder/__init__.py
binder/permissions/views.py
binder/plugins/token_auth/management/commands/create_user_token.py
binder/plugins/token_auth/management/commands/delete_user_token.py
binder/plugins/token_auth/models.py
binder/plugins/views/multi_request.py
binder/tests/plugins/test_multi_request.py
binder/tests/plugins/test_token_auth.py
binder/tests/test_inheritance.py
binder/tests/test_pagination.py
binder/tests/testapp/urls.py
binder/tests_discoverer.py
binder/views.py

Automatically imports all unittests, so that it doesn't need to be done manually.
How it works:
in main/tests/__init__.py add the following:
- `from binder import load_tests`
- ???
- Profit
A bit deeper how it works:
- This loads all the apps in binder
- It tries to see if the tests/ directory exists
- If it exists, it automatically loads all the tests
Does not run the tests on apps that are not in the app directory

Add automated test discoverer to binder

---

binder/router.py

Old:
```
from binder.router import Router
from binder.views import ModelView
import cyrm.views  # noqa
import base.orders.views  # noqa
import ib.ib_orders.views  # noqa
....
import base.planning.views # noqa
router = Router().register(ModelView)
api_urls = [
re_path('^', include(router.urls)),
]
```
New:
```
from binder.router import Router
router = Router.bootstrap()
api_urls = [
re_path('^', include(router.urls)),
]
```

Automatic views importing in router

---

CHANGELOG.md
binder/views.py

This avoids requiring a subquery in the with_ids array_agg call.
Without a subselect, things are a lot faster!
There are a few situations in virtual relations where this is not the
best way, but not many projects use virtual relations and most of
these cases can be worked around in Django 3 due to being able to
filter on boolean expressions anyway...

[WIP] Refactor _filter_field and _filter_relation to return Q objects.

---

binder/websocket.py
tests/test_websocket.py

Allows to set RabbitMQ settings for the HT triggers
Breaking change: 
- HIGH_TEMPLAR_URL needs to be set in order for old HT messages to be triggered

Add RabbitMq support for HT

---

binder/plugins/views/userview.py
tests/plugins/test_userview.py
tests/testapp/views/user.py

Due to changes in _parse_filter in both userview and general view which different and not compatible atm binder is broken. 
This PR adds tests for the functionality and fixes the issue, it does assume that the userview never has to have distinct elements. This is less optimized then detecting when distinct can be used but does ensure all data is sent that is needed.

Fix userview _parse_filter, which currently is broken and thus breaks binder

---

binder/views.py
docker-compose.yml
tests/test_multi_put.py
tests/test_permission_view.py

This add the keys `deletions` and `with_deletions` to multiput.
I chose to do this in 2 seperate keys instead of just one key with the functionality of `with_deletions` to be consistent with how we now do it on the data side with `data` and `with`.
While I was working on this I made some small change to the parsing of multiput for data as well, namely that the `data` key is now optional to be consisten with the new `deletions` key.

Add deletions to multiput

---

binder/views.py

This allows the AggStrategy to be set by the application in case of another database then mysql or postgres (In this particular case Mssql)

Abstract AggStrategy to make it extensible

---

binder/views.py

So @abzainuddin and me thought that some fields were automatically ignored by binder. Apparantly they were not but there is a read only field error. However some additions from that were missing.
I think ignoring them is not necessary anymore as of https://github.com/CodeYellowBV/mobx-spine/pull/80 since we can now more easily handle which fields get sent on the frontend.

Make read only error a bit stricter

---

binder/views.py

Instead of doing one query per object, do one query per model to lock
all the objects.  This should improve performance of multi-PUT a bit.
This is a refactor, not a semantic change, so this also adds a note
regarding an inconsistency in how view permissions are not checked
during multi-PUT, while they are checked during singular PUT/POST.
NOTE: This branch is already pretty old. I had intended to start some serious work in here to reduce all queries but I got sidetracked, so I think it's best if we merge this now and I can continue this work at some later point.

Reduce number of queries performed by MultiPUT when locking objects

---

binder/models.py
binder/plugins/views/userview.py
binder/views.py
tests/test_annotations.py
tests/test_set_nullable_relation.py
tests/testapp/models/animal.py
tests/testapp/views/user.py

This adds a wrapper `ContextAnnotation` that can be used to wrap a function that accepts a request object as it's only parameter and returns a Django query expression. This can be used to for example alter annotations based on the current user.
This PR does break a few things.
- A lot of methods now need the request object that previously did not, this however should be very trivial to migrate.
- The annotate function now requires a request object, we should see if this is often called outside of a request context in application code.

Add context aware annotations

---

binder/views.py
tests/test_order_by.py

When fetching relations through "with", we used to skip complex
Meta.ordering expressions because they couldn't be prefixed with the
relation's name.
This implementation calls "deconstruct" from the deconstructible
decorator which is used on all serializable values.  Meta.ordering
must be serializable by definition, because it needs to usable in
migrations, so we can safely rely on that for the order by stuff.

Get rid of workaround for complex sorting and replace it with a proper implementation

---

CHANGELOG.md
binder/models.py
binder/views.py
tests/filters/test_uuid_field_filtering.py
tests/plugins/test_csvexport.py
tests/plugins/test_imageview.py
tests/test_history.py
tests/test_model_view_basics.py
tests/test_multi_put.py
tests/test_pagination.py
tests/test_postgres_fields.py
tests/test_soft_and_hard_deletes.py
tests/test_validation_errors.py
tests/test_websocket.py
tests/testapp/models/zoo.py

This implements #128 by calling `full_clean` in `BinderModel`'s `save()` method.

Full clean builtin

---

CHANGELOG.md
binder/models.py
binder/plugins/loaded_values.py
binder/views.py
tests/filters/test_uuid_field_filtering.py
tests/plugins/test_csvexport.py
tests/plugins/test_imageview.py
tests/test_history.py
tests/test_model_view_basics.py
tests/test_multi_put.py
tests/test_pagination.py
tests/test_postgres_fields.py
tests/test_soft_and_hard_deletes.py
tests/test_validation_errors.py
tests/test_websocket.py
tests/testapp/models/zoo.py

This depends on #141 so please review that first (or close it and merge this one)

Reduced queries in full clean

---

binder/views.py
tests/test_m2m_store_errors.py

Currently in binder when a multiput is performed with a base model and m2m models django breaks if the base model is invalid. Reason for this is that the saving of the base model fails, but the saving of the m2m model is still tried after this.
We do sill want to check the m2m models for validation errors aswell, so not performing any of these checks is not an option. For this reason checking if the base model has an id is the best method .

Fix M2M Saving breaking when the base model save fails

---

binder/decorators.py
binder/view_logger.py
tests/test_decorators.py
tests/testapp/urls.py
tests/testapp/views/handle_exceptions.py

Adds a decorator `binder.decorators.handle_exceptions` that handles `BinderException`s in view functions in the same way as the `BinderView` does (Abort transaction and turn exception into a response using the request.).
Adds a decorator `binder.decorators.allowed_methods` that given some http method names wraps a view function to throw a `BinderMethodNotAllowed` when the request method is not one of these methods (Advantage over the django decorators for this is that this conforms to the standard binder error format.).
Also moves the decorator `binder.view_logger.view_logger` to `binder.decorators.view_logger`. The old path is still importable for backwards compatibility but will give a warning.

Add decorators module

---

binder/plugins/token_auth/middleware.py
binder/plugins/views/multi_request.py
docs/plugins/tokenauth.md
tests/__init__.py
tests/plugins/test_token_auth.py

It seems that token auth usage does not completely skip csrf auth. This
commit does skip it, and adds a test that POSTing using token auth
completely skips csrf.

Force skipping csrf when using token auth

---

binder/models.py
binder/views.py
docs/models.md
tests/test_binder_file_field.py
tests/testapp/models/zoo.py

Now binder renames the files to use the id instead of the name.

Use original filename

---

binder/views.py
tests/test_m2m_store_errors.py
tests/testapp/models/contact_person.py
tests/testapp/models/zoo.py

Currently, when there are model validation errors, thrown by `clean()` for example, we still try to go on and save related fields of the four 'reverse relationship' types: reverse fk, reverse one to one, m2m and reverse m2m. I created four tests that try to reproduce these situations. Bob already added a check for the m2m case, but I think that this check is needed before the `_store_m2m_fields` method is even called, because my test fail in those cases.
See T30296 for more context.

When model validation has errors, leave reverse relations

---

binder/views.py

Add `TRANSACTION_DATABASES` setting, to allow for multiple databases to be in a transaction. Defaults to only the default database

Add support for multiple writable databases

---

binder/views.py
tests/test_binder_file_field.py

So there is no difference between `.jpg` or `.JPG`.
Perhaps better to use FileExtensionValidator, but for now it's a quick fix.

Make allowed_extensions case insensitive

---

binder/views.py

I notice that I very often need the queryset with all the filtering/sorted etc applied in list routes. Currently you have to copy paste this logic from the get method, I now moved it to a seperate method called get_filtered_queryset that the get method now also uses.
This does not change any existing behaviour, it only moves a part to a seperate method.

Split logic to get filtered queryset into seperate method

---

binder/views.py
tests/test_file_uploads.py

Currently there is a quite nasty bug in master.
- Suppose there is a model called `Model` with a file field called `file`.
- If we have 2 instances of this model with id 1 and id 2.
- If the field `file` is fileld for the model with id 1.
- If we do `PUT /api/model/2/ {"file": "/api/model/1/file/"}` this will now save a reference to the same file in the database for model 2 as for model 1.
- If we now update the file on model 2 the old file will be deleted.
- Model 1 now has a reference to a file that does not exist.

File upload copy fix

---

binder/models.py
tests/test_binder_file_field.py

Some files were not closed properly, which causes at some point too many
open files on the server. This was fixed somewhere down the line, this
adds a regression test.

Add test for unclosed files bug

---

binder/permissions/views.py
tests/test_permission_view.py

So we often combine Q-objects from different view scopes to form one big Q-object with an OR. This is all fine and dandy but can result in redundant Q-objects that can lead to redundant joins that can lead to big performance hits.
Example from rex:
```python
class CallView(PermissionView):
def _scope_view_client(self, request):
return Q(client=request.user.client)
def _scope_view_own(self, request):
return Q(client=request.user.client, legs__contact__user=request.user)
```
In this case if a user has both scopes `client` and `own`, the Q-object of `own` does not add anything and results in a few joins that are not needed.
With the changes in this PR binder automatically detects that the `own`-scope does not add anything over the `client`-scope in this case and excludes it from the combined …

Smart combine Q-objects with or to remove redundancy

---

binder/models.py
binder/views.py
tests/test_model_view_basics.py
tests/test_multi_put.py
tests/testapp/models/__init__.py
tests/testapp/models/donor.py
tests/testapp/views/__init__.py
tests/testapp/views/donor.py

Currently, when doing a multiput on a model with as default ordering containing a foreign key, a postgres is shown.
The error states "For update cannot be applied to the nullable side of an outerjoin"
This pull request fixes this

Fix bug with nullable default orderings in multi put

---

binder/views.py
docs/api.md
tests/test_after.py

This adds a special filter that allows you to filter for records that come after a record with a certain id in respect to the other filters/ordering. This is very useful for querying extra records when lazy loading.

Add special after filter

---

docker-compose.yml
setup.py

Local testing uses a different package install process then the CI. To prevent us running postgres 12 default while local testing bu use 11 instead we must also use django 3.
To enable this we in the setup.py which is used for local testing require a django 3 version instead of a django 3 or 4 version. Since django 4 is only postgres 12+ compatible.

Make local testing use django 3.

---

binder/views.py
docker-compose.yml
setup.py
tests/test_inheritance.py
tests/testapp/models/__init__.py
tests/testapp/models/pet.py
tests/testapp/views/__init__.py
tests/testapp/views/pet.py

This PR fixes a bug where in some scenarios, when using multiput on a models that have proxy submodel(a submodel without a db table) it would fail on trying to override superclass for that model instance(`_multi_put_override_superclass` method in the `views.py` file).
Example stacktrace of the error:
```
Traceback (most recent call last):
File "/binder/tests/test_inheritance.py", line 93, in test_create_lion_with_animal_and_zoo
response = self.client.put(
^^^^^^^^^^^^^^^^
File "/binder/.eggs/Django-4.2.11-py3.12.egg/django/test/client.py", line 1026, in put
response = super().put(
^^^^^^^^^^^^
File "/binder/.eggs/Django-4.2.11-py3.12.egg/django/test/client.py", line 537, in put
return self.generic(
^^^^^^^^^^^^^
File "/binder/.eggs/Django-4.2.11-py3.12.egg/django/test/client.py", line …
```

Fix multiput with proxy submodels

---

binder/models.py
binder/views.py
docs/models.md
tests/__init__.py
tests/test_binder_file_field.py
tests/testapp/models/zoo.py
tests/testapp/views/zoo.py

This PR adds the Boolean option `serve_directly` to `BinderFileField` and `BinderImageField`, with the default value `False`.
When set to `True`, a special header is added to HTTP responses that delegates the serving of the affected files to the web server (e.g. Nginx).

Support serving files directly

---

Dockerfile
binder/views.py
tests/test_stats.py
tests/testapp/models/animal.py
tests/testapp/views/animal.py

When using the same annotations twice as stats, it does not work. See `tests/test_stats/StatsTest/test_animals_annotation_duplicates`
Also, setuptools was deprecated for testing in version py3, so upped version to py3.9

binder stats with annotations

---

binder/plugins/views/csvexport.py
tests/plugins/test_csvexport.py

Previously, the Excel export created a new sheet after creating the workbook, but the Workbook constructor already creates a default sheet. This caused customers to open the export and see the first, empty sheet, thinking the export was broken rather than clicking on the second sheet.

Prevent Excel export from generating two sheets

---

.github/workflows/ci.yml
binder/models.py
ci-requirements.txt
setup.py

- Update github ci testing matrix
Note that python 3.8 and django 5 are not compatible so add an exception
not to run that combination
- Update timezone import
Starting from django 5 the utc timezone should be imported from the
default python datetime library instead of the django specific library
- Fix get_fixed_timezone
The get_fixed_timezone method however is still needed from the django
library so import that seperatly

Django 5 update
